$(document).ready(function(){
  $("#heading1").click(function(){
    $("#hidden1").slideToggle();
  });
  $("#heading2").click(function(){
    $("#hidden2").slideToggle();
  });
  $("#heading3").click(function(){
    $("#hidden3").slideToggle();
  });
  $("#heading4").click(function(){
    $("#hidden4").slideToggle();
  });
});
