$(document).ready(function(){
  $("#heading1").click(function(){
    $("#hidden1").slideDown();
  });
  $("#heading2").click(function(){
    $("#hidden2").slideDown();
  });
  $("#heading3").click(function(){
    $("#hidden3").slideDown();
  });
  $("#heading4").click(function(){
    $("#hidden4").slideDown();
  });
});
